# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adbb1aefb9dbdfaa7b4d687d1f15d4adc93539814e704009be14e231d6fcf88acd6146f9118edff08128a5d8cbbea38ee0a0ecb2521cea073bdcde7b81d62397

test:
  secret_key_base: 080353a1c3b1053c011592907cb5f7c29b6257891ecdb4c661ba39ff65208891385f9c3cd51b3153bb4763343c9b2e0d97d204555d538966c33efb3829ffc0fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
